// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var View$ReactHooksTemplate = require("./View.bs.js");
var Create$ReactHooksTemplate = require("./Create.bs.js");
var Explore$ReactHooksTemplate = require("./Explore.bs.js");

((require('./App.css')));

function App(Props) {
  return React.createElement("div", undefined, React.createElement("h1", {
                  className: "is-size-2 has-text-centered"
                }, "3 pane view"), React.createElement("div", {
                  className: "columns"
                }, React.createElement("div", {
                      className: "column has-background-white-ter"
                    }, React.createElement(Create$ReactHooksTemplate.make, { })), React.createElement("div", {
                      className: "column has-background-grey-lighter"
                    }, React.createElement(View$ReactHooksTemplate.make, { })), React.createElement("div", {
                      className: "column has-background-grey-light"
                    }, React.createElement(Explore$ReactHooksTemplate.make, { }))));
}

var make = App;

exports.make = make;
/*  Not a pure module */
