// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");

function Component1(Props) {
  var message = Props.message;
  var children = Props.children;
  var match = React.useState((function () {
          return 0;
        }));
  var setCount = match[1];
  var count = match[0];
  var handleClick = function (_event) {
    console.log("clicked!");
    return Curry._1(setCount, (function (param) {
                  return count + 1 | 0;
                }));
  };
  return React.createElement("div", undefined, children, React.createElement("button", {
                  onClick: handleClick
                }, message + String(count)));
}

var make = Component1;

exports.make = make;
/* react Not a pure module */
