// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");
var Belt_List = require("bs-platform/lib/js/belt_List.js");
var Entry$ReactHooksTemplate = require("./Entry.bs.js");

function Create(Props) {
  var match = React.useState((function () {
          return /* :: */[
                  "One",
                  /* :: */[
                    "Two",
                    /* [] */0
                  ]
                ];
        }));
  var todos = Belt_List.map(match[0], (function (item) {
          return React.createElement(Entry$ReactHooksTemplate.make, {
                      label: item
                    });
        }));
  return React.createElement("div", undefined, React.createElement("h1", {
                  className: "is-size-2"
                }, "Create"), React.createElement("form", {
                  className: "box",
                  action: ""
                }, React.createElement("div", {
                      className: "field"
                    }, React.createElement("div", {
                          className: "control"
                        }, React.createElement("input", {
                              className: "input",
                              placeholder: "label"
                            }))), React.createElement("div", {
                      className: "field"
                    }, React.createElement("div", {
                          className: "control"
                        }, React.createElement("input", {
                              className: "input",
                              placeholder: "value"
                            }))), React.createElement("div", {
                      className: "field"
                    }, React.createElement("button", {
                          className: "button is-success",
                          onClick: (function (_event) {
                              return /* () */0;
                            })
                        }, "Add"))), React.createElement("ul", {
                  className: "todo-list"
                }, Belt_List.toArray(todos)));
}

var make = Create;

exports.make = make;
/* react Not a pure module */
