// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");
var Belt_List = require("bs-platform/lib/js/belt_List.js");
var Entry$ReactHooksTemplate = require("./Entry.bs.js");

function Create(Props) {
  var match = React.useState((function () {
          return /* :: */[
                  "AA",
                  /* :: */[
                    "BB",
                    /* [] */0
                  ]
                ];
        }));
  var setItems = match[1];
  var items = match[0];
  var match$1 = React.useState((function () {
          return "";
        }));
  var setLabelValue = match$1[1];
  var labelValue = match$1[0];
  var match$2 = React.useState((function () {
          return "";
        }));
  var setItemValue = match$2[1];
  return React.createElement("div", undefined, React.createElement("h1", {
                  className: "is-size-2"
                }, "Create"), React.createElement("form", {
                  className: "box"
                }, React.createElement("div", {
                      className: "field"
                    }, React.createElement("div", {
                          className: "control"
                        }, React.createElement("input", {
                              className: "input",
                              placeholder: "label",
                              onChange: (function (param) {
                                  return Curry._1(setLabelValue, param.target.value);
                                })
                            }))), React.createElement("div", {
                      className: "field"
                    }, React.createElement("div", {
                          className: "control"
                        }, React.createElement("input", {
                              className: "input",
                              placeholder: "value",
                              onChange: (function (param) {
                                  return Curry._1(setItemValue, param.target.value);
                                })
                            }))), React.createElement("div", {
                      className: "field"
                    }, React.createElement("a", {
                          className: "button is-success",
                          onClick: (function (_event) {
                              return Curry._1(setItems, (function (param) {
                                            return /* :: */[
                                                    labelValue,
                                                    items
                                                  ];
                                          }));
                            })
                        }, "Add"))), React.createElement("ul", undefined, Belt_List.toArray(Belt_List.map(items, (function (item) {
                            return React.createElement(Entry$ReactHooksTemplate.make, {
                                        label: item,
                                        key: item
                                      });
                          })))));
}

var make = Create;

exports.make = make;
/* react Not a pure module */
