// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function Entry(Props) {
  var label = Props.label;
  return React.createElement("li", undefined, label);
}

var make = Entry;

exports.make = make;
/* react Not a pure module */
