// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var React = require("react");

function Explore(Props) {
  return React.createElement("h1", {
              className: "is-size-2"
            }, "Explore");
}

var make = Explore;

exports.make = make;
/* react Not a pure module */
