// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var React = require("react");

function View(Props) {
  var match = React.useState((function () {
          return 0;
        }));
  var setCount = match[1];
  var count = match[0];
  return React.createElement("div", undefined, React.createElement("h1", {
                  className: "is-size-2"
                }, "View"), React.createElement("button", {
                  onClick: (function (_event) {
                      return Curry._1(setCount, (function (param) {
                                    return count + 1 | 0;
                                  }));
                    })
                }, "Clicked " + (String(count) + " times")));
}

var make = View;

exports.make = make;
/* react Not a pure module */
